// Code generated by github.com/spiffdev/gqlgen, DO NOT EDIT.

package generated

type Input struct {
	N *int `json:"n,omitempty"`
}

type Input64 struct {
	N *int `json:"n,omitempty"`
}

type Query struct {
}

type Result struct {
	N int `json:"n"`
}

type Result64 struct {
	N int `json:"n"`
}
