// Code generated by github.com/spiffdev/gqlgen, DO NOT EDIT.

package contextpropagation

type Query struct {
}

type Todo struct {
	Text    string       `json:"text"`
	Context *TodoContext `json:"context"`
}

type TodoContext struct {
	Value *string `json:"value,omitempty"`
}
